DROP DATABASE IF EXISTS techBlogMVC_db;
CREATE DATABASE IF NOT EXISTS techBlogMVC_db;

CREATE TABLE IF NOT EXISTS "user" (
    "user_id" SERIAL PRIMARY KEY,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(100) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
);
